site_name: Inuitive-paper-daily

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes

repo_url: https://github.com/wanghaisheng/Inuitive-paper-daily

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang:
        - en
        - ja

extra:
  analytics:
    provider: google
    property: UA-145083103-1
